Added team page.Issue no(#7).
fossiiita/humblefoolcup pull request #38
Opened 2017-01-25 13:14 UTC by Anupam-dagar

2017-01-25 13:15 UTC, gauthamzz commented
could you post a live demo url

2017-01-25 13:19 UTC, Anupam-dagar commented
Oh,i forgot to comment that.
Live link:
https://anupam-dagar.github.io/humblefoolcup/team.html

2017-01-25 13:21 UTC, gauthamzz commented
@Anupam-dagar could we try a better cards. It doesnt look that good

2017-01-25 13:22 UTC, Anupam-dagar commented
Ok,I will make them better.

2017-01-28 16:54 UTC, gauthamzz requested changes

2017-01-28 16:54 UTC, gauthamzz commented on team.html
> +
please provide link for humble fool tribute page also over here

2017-01-30 13:38 UTC, magician03 commented
@Anupam-dagar , thanks for your work.

Your branch seems to have merge conflicts. Please rebase/ merge with current master. :)

2017-01-30 19:05 UTC, Anupam-dagar commented
I am remaking it,header and footer are left.I will fix merge conflicts after it is ready.

2017-01-31 12:01 UTC, closed without merging