Added preloader
fossiiita/humblefoolcup pull request #51
Opened 2017-01-30 14:46 UTC by aswanthkoleri

check it out : [view new loader](https://aswanthkoleri.github.io/humblefoolcup/)

2017-01-30 17:12 UTC, magician03 commented on css/main.css
> +h1 {
What is this needed for, it is overwriting the color of headers in index.html. Add class to DOM elements and style those by specifying the class. Cross for other tags and specifiers too.

2017-01-30 17:16 UTC, magician03 commented
@aswanthkoleri , your stylesheet is overwriting the styles of existing DOM, mentioned the same in inline review.
Name your files as `loader.css` and `loader.js`. It would be more clear and consistent that way

2017-01-30 17:45 UTC, gauthamzz requested changes

2017-01-30 17:45 UTC, gauthamzz commented on js/main.js
> +/*
please remove this part

2017-01-31 06:56 UTC, magician03 commented
Duplicate PR of #52 , closing

2017-01-31 06:56 UTC, closed without merging