Added team page.Issue no.(#7)
fossiiita/humblefoolcup pull request #53
Opened 2017-01-31 12:04 UTC by Anupam-dagar

This PR is for the issue #7 

https://anupam-dagar.github.io/humblefoolcup/
Added team page.
I am not able to make header and footer responsive.

Note - After this PR gets accepted, please add your contribution to scores.yml . Refer to README for more details.

2017-01-31 12:13 UTC, Anupam-dagar commented
why header looks different on pc and live link....
![screenshot from 2017-01-31 17-42-36](https://cloud.githubusercontent.com/assets/21174572/22464420/c4ce3800-e7dc-11e6-970f-fa6f8a856b95.png)
![screenshot from 2017-01-31 17-42-44](https://cloud.githubusercontent.com/assets/21174572/22464421/c4cf5618-e7dc-11e6-8209-fdce0f2ffb0e.png)

2017-01-31 12:40 UTC, pradeepgangwar commented
That "in memory Harsha Suryanarayana" of line remains fixed and moves with page.

Although it is not so  visible but can be clearly visualize through careful observation.
Make it appear only when page is scrolled down not like one it is now.

Make this change @Anupam-dagar

2017-01-31 12:41 UTC, Anupam-dagar commented
I know about that, i tried, i need help regarding these.

2017-01-31 12:54 UTC, pradeepgangwar commented
i will see code and reply if i have any help to offer :)

2017-01-31 16:23 UTC, gauthamzz requested changes
@magician03 review this for unresponsiveness

2017-01-31 16:23 UTC, gauthamzz commented on team.html
> +    <li><a href="/"><span>Home</span></a></li>
Please provide links

2017-01-31 16:23 UTC, gauthamzz commented on css/team.css
> +@import 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css';
download these and keep them in css folder

2017-02-05 02:57 UTC, gauthamzz commented
@Anupam-dagar we need this done ASAP , please give me update

2017-02-07 06:39 UTC, Anupam-dagar commented
I wll make it responsive,
should i need to change the design also.
I will make sure next update get accepted.
I will complete it by today.

2017-02-13 14:51 UTC, gauthamzz commented
remove the header and menu from team page

2017-02-13 15:07 UTC, Anupam-dagar commented
https://anupam-dagar.github.io/humblefoolcup/team.html
Will this work.
![screenshot from 2017-02-13 20-35-42](https://cloud.githubusercontent.com/assets/21174572/22888516/06ce8454-f22c-11e6-8954-2370347d152a.png)

2017-02-13 15:33 UTC, Anupam-dagar commented
![screenshot from 2017-02-13 21-01-57](https://cloud.githubusercontent.com/assets/21174572/22889597/b63b42f8-f22f-11e6-8d07-8d3471dacd13.png)
Done.

2017-02-13 21:57 UTC, merged